from sqlalchemy import Column, Integer, Float, ForeignKey, DateTime, String, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.database import Base


class EnvelopeData(Base):
    """
    One point on a well's operating envelope: at a given gross liquid rate,
    the tubing head pressure, the flowline pressure and the minimum pressure
    for critical flow through the bean.

    `source` distinguishes points read verbatim from the workbook's
    'Envelope Data' sheet from points generated by a bean correlation, so the
    UI can label modelled curves as such.
    """

    __tablename__ = "envelope_data"

    SOURCE_WORKBOOK = "workbook"
    SOURCE_MODEL = "model"

    id = Column(Integer, primary_key=True, index=True)
    well_id = Column(Integer, ForeignKey("wells.id"), nullable=False)
    test_data_id = Column(Integer, ForeignKey("test_data.id"))
    gross_rate = Column(Float)      # stb/d
    thp_curve = Column(Float)       # tubing head pressure at that rate, psig
    flp = Column(Float)             # flowline pressure, psig
    critical_flow = Column(Float)   # minimum THP for critical flow, psig
    source = Column(String(20), default=SOURCE_WORKBOOK, index=True)
    computed_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    well = relationship("Well", back_populates="envelope_data")
    test_data = relationship("TestData")

    __table_args__ = (
        Index("ix_envelope_data_well_source", "well_id", "source"),
    )
